In [15]:
import numpy as np
from scipy import spatial
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

import pandas as pd
from scipy.spatial import distance

In [4]:
# I need to extract the embeddings for these words
words = ['cat','dog','frog']

embeddings_dict = {}
#glove = open("data/glove.42B.300d.txt", 'r', encoding="utf-8")
#glove.close()

In [5]:
# !head data/glove.42B.300d.txt

glove = pd.read_csv("data/glove.6B.50d.txt", delimiter=' ', header=None, quoting=3)

In [6]:
glove.describe()

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
count,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,...,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000
mean,-0.129201,-0.288662,-0.012249,-0.056767,-0.202111,-0.083890,0.333597,0.160451,0.038675,0.178331,...,0.139920,-0.174463,-0.080118,0.084952,-0.010416,-0.137049,0.201271,0.100693,0.006530,0.016851
std,0.636704,0.613996,0.612466,0.624203,0.639919,0.665588,0.623440,0.608380,0.645970,0.619217,...,0.570008,0.608277,0.608691,0.629454,0.627500,0.620790,0.558487,0.615509,0.600067,0.623284
min,-5.459300,-3.630000,-3.883500,-4.625200,-4.054900,-5.309800,-3.427100,-3.934900,-3.792700,-3.816300,...,-3.910200,-3.484900,-3.139300,-3.788800,-5.194100,-3.513300,-3.077500,-4.723100,-4.615100,-3.915300
25%,-0.534942,-0.683262,-0.407460,-0.463890,-0.611740,-0.492560,-0.059535,-0.213180,-0.360853,-0.204772,...,-0.220583,-0.576230,-0.474930,-0.320230,-0.408950,-0.532460,-0.151080,-0.285080,-0.373642,-0.392800
50%,-0.133555,-0.315320,-0.009604,-0.082614,-0.207160,-0.074543,0.348130,0.189620,0.043624,0.195080,...,0.133390,-0.201420,-0.092212,0.097806,-0.012346,-0.156920,0.205290,0.102910,0.001320,0.002287
75%,0.274583,0.079589,0.386820,0.325983,0.205995,0.333940,0.737252,0.564470,0.443953,0.576370,...,0.490880,0.199200,0.308303,0.500650,0.388230,0.238690,0.557160,0.485930,0.385100,0.416023
max,3.874000,4.018300,3.977500,5.310100,4.601400,4.868700,3.863700,3.627900,3.973400,3.787900,...,3.923000,4.508700,3.948300,5.075600,3.532800,4.589400,4.234500,4.541900,4.822800,4.178500

In [7]:
glove.head()

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
0,the,0.418000,0.249680,-0.41242,0.12170,0.34527,-0.044457,-0.49688,-0.17862,-0.00066,...,-0.298710,-0.157490,-0.347580,-0.045637,-0.44251,0.187850,0.002785,-0.184110,-0.115140,-0.78581
1,",",0.013441,0.236820,-0.16899,0.40951,0.63812,0.477090,-0.42852,-0.55641,-0.36400,...,-0.080262,0.630030,0.321110,-0.467650,0.22786,0.360340,-0.378180,-0.566570,0.044691,0.30392
2,.,0.151640,0.301770,-0.16763,0.17684,0.31719,0.339730,-0.43478,-0.31086,-0.44999,...,-0.000064,0.068987,0.087939,-0.102850,-0.13931,0.223140,-0.080803,-0.356520,0.016413,0.10216
3,of,0.708530,0.570880,-0.47160,0.18048,0.54449,0.726030,0.18157,-0.52393,0.10381,...,-0.347270,0.284830,0.075693,-0.062178,-0.38988,0.229020,-0.216170,-0.225620,-0.093918,-0.80375
4,to,0.680470,-0.039263,0.30186,-0.17792,0.42962,0.032246,-0.41376,0.13228,-0.29847,...,-0.094375,0.018324,0.210480,-0.030880,-0.19722,0.082279,-0.094340,-0.073297,-0.064699,-0.26044

In [8]:
glove[ glove[0] == 'cat' ]

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
5450,cat,0.45281,-0.50108,-0.53714,-0.015697,0.22191,0.54602,-0.67301,-0.6891,0.63493,...,-0.097479,0.48138,-0.43352,0.69455,0.91043,-0.28173,0.41637,-1.2609,0.71278,0.23782

In [9]:
cat = glove[ glove[0] == 'cat' ]
dog = glove[ glove[0] == 'dog' ]
frog = glove[ glove[0] == 'frog' ]

In [10]:
cat,dog,frog

(       0        1        2        3         4        5        6        7   \
 5450  cat  0.45281 -0.50108 -0.53714 -0.015697  0.22191  0.54602 -0.67301

           8        9   ...        41       42       43       44       45  \
 5450 -0.6891  0.63493  ... -0.097479  0.48138 -0.43352  0.69455  0.91043

            46       47      48       49       50
 5450 -0.28173  0.41637 -1.2609  0.71278  0.23782

 [1 rows x 51 columns],
        0        1        2        3        4        5        6       7   \
 2926  dog  0.11008 -0.38781 -0.57615 -0.27714  0.70521  0.53994 -1.0786

            8       9   ...        41       42       43       44      45  \
 2926 -0.40146  1.1504  ... -0.086199  0.24068 -0.64819  0.83549  1.2502

            46       47       48      49       50
 2926 -0.51379  0.04224 -0.88118  0.7158  0.38519

 [1 rows x 51 columns],
          0        1        2        3        4        5        6       7   \
 12260  frog  0.61038 -0.20757 -0.71951  0.89304  0.32482  0.76564  0.1814

             8        9   ...       41       42       43       44      45  \
 12260 -0.33086  0.79173  ... -0.66394 -0.18508 -0.87174  0.30782  1.2839

             46       47     48       49       50
 12260 -0.14884  0.62178 -1.509  0.14582 -0.31682

 [1 rows x 51 columns])

In [13]:
catv = np.array( cat.values[0][1:] )
dogv = np.array( dog.values[0][1:] )
frogv = np.array( frog.values[0][1:] )

In [16]:
distance.euclidean(catv,dogv)

1.8846031066726727

In [17]:
def getv(name):
    word = glove[glove[0]==name]
    return np.array( word.values[0][1:] )

In [20]:
tadpolev = getv('tadpole')
toadv = getv('toad')

In [19]:
distance.euclidean(frogv,tadpolev)

4.37459699754767

In [21]:
distance.euclidean(toadv,frogv)

3.0397537609993277

In [22]:
bigv = getv('big')
largev = getv('large')

In [23]:
distance.euclidean(bigv,largev)

4.216144564787479

In [ ]:
#Works if I have an embeddings_dict
#def find_closest_embeddings(embedding):
#    return sorted(embeddings_dict.keys(), key=lambda word: spatial.distance.euclidean(embeddings_dict[word], embedding))